version: "3.8"

services:
  backend:
    build: ./backend
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=videos
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./backend:/app
    restart: always
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: videos
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    container_name: vite_app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - backend

  celery:
    build: ./backend
    container_name: celery_worker
    command: celery -A celery_app worker --loglevel=info  # ✅ use celery_app, not tasks
    depends_on:
      - redis
      - backend
    volumes:
      - ./backend:/app
    env_file:
      - .env  # ✅ optional, useful if tasks use env vars

volumes:
  pgdata:
